# -*- coding: utf-8 -*-
"""Extract and Categorize Tasks from Unannotated Text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvJJ08am7Xxk75XnVMhNUntX6Sbio7Um
"""

!pip install spacy nltk
!python -m spacy download en_core_web_sm

import spacy
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
import re
from collections import defaultdict

# Download all required NLTK resources
def download_nltk_resources():
    resources = ['punkt', 'stopwords', 'averaged_perceptron_tagger']
    for resource in resources:
        try:
            nltk.download(resource, quiet=True)
        except Exception as e:
            print(f"Error downloading {resource}: {str(e)}")
            return False
    return True

# Initialize NLTK resources
if not download_nltk_resources():
    raise RuntimeError("Failed to download required NLTK resources")

try:
    # Load spaCy model
    nlp = spacy.load('en_core_web_sm')
except OSError:
    print("Downloading spaCy model...")
    import subprocess
    subprocess.run(["python", "-m", "spacy", "download", "en_core_web_sm"])
    nlp = spacy.load('en_core_web_sm')

class TaskExtractor:
    def __init__(self):
        try:
            self.stop_words = set(stopwords.words('english'))
        except LookupError:
            print("Downloading stopwords...")
            nltk.download('stopwords')
            self.stop_words = set(stopwords.words('english'))

        # Define action verbs that commonly indicate tasks
        self.action_verbs = {
            'complete', 'finish', 'submit', 'review', 'prepare', 'create',
            'update', 'check', 'clean', 'buy', 'send', 'write', 'schedule',
            'organize', 'implement', 'develop', 'analyze', 'report'
        }
        # Define modal verbs that often indicate tasks
        self.modal_verbs = {
            'must', 'should', 'need', 'have to', 'has to', 'needs to',
            'required to', 'supposed to'
        }

    def preprocess_text(self, text):
        """Clean and preprocess the input text."""
        # Convert to lowercase
        text = text.lower()
        # Remove special characters but keep necessary punctuation
        text = re.sub(r'[^a-zA-Z0-9\s.,!?]', '', text)
        return text

    def extract_date_info(self, sentence):
        """Extract date/deadline information from the sentence."""
        doc = nlp(sentence.lower())
        date_info = None

        # Pattern for "by X pm/am" or "by X:XX pm/am"
        time_pattern = re.compile(r'by\s+\d{1,2}(?::\d{2})?\s*(?:pm|am)')
        time_match = time_pattern.search(sentence.lower())

        if time_match:
            date_info = time_match.group()
        else:
            # Look for temporal expressions
            date_keywords = ['today', 'tomorrow', 'next week', 'tonight', 'morning',
                           'afternoon', 'evening', 'monday', 'tuesday', 'wednesday',
                           'thursday', 'friday', 'saturday', 'sunday']
            words = sentence.lower().split()
            for keyword in date_keywords:
                if keyword in words:
                    date_info = keyword
                    break

            if not date_info:
                for ent in doc.ents:
                    if ent.label_ in ['TIME', 'DATE']:
                        date_info = ent.text
                        break

        return date_info

    def extract_person(self, sentence):
        """Extract person/entity responsible for the task."""
        doc = nlp(sentence)

        # First check for named entities
        for ent in doc.ents:
            if ent.label_ == 'PERSON':
                return ent.text

        # Check for subject of the sentence
        for token in doc:
            if token.dep_ == 'nsubj' and not token.text.lower() in self.stop_words:
                return token.text

        return None

    def categorize_task(self, task):
        """Categorize the task based on keywords."""
        task_lower = task.lower()
        categories = defaultdict(int)

        # Define category keywords
        category_keywords = {
            'purchase': ['buy', 'purchase', 'order', 'shop'],
            'cleaning': ['clean', 'wash', 'organize', 'tidy'],
            'communication': ['send', 'email', 'call', 'contact', 'write'],
            'review': ['review', 'check', 'analyze', 'evaluate'],
            'development': ['create', 'develop', 'implement', 'build'],
            'deadline': ['submit', 'complete', 'finish']
        }

        # Score each category based on keyword matches
        for category, keywords in category_keywords.items():
            for keyword in keywords:
                if keyword in task_lower:
                    categories[category] += 1

        # Return the category with highest score, or 'general' if no matches
        if categories:
            return max(categories.items(), key=lambda x: x[1])[0]
        return 'general'

    def is_task_sentence(self, sentence):
        """Determine if a sentence contains a task."""
        try:
            # Convert sentence to lowercase for easier matching
            sentence_lower = sentence.lower()

            # Check for modal verbs
            if any(modal in sentence_lower for modal in self.modal_verbs):
                return True

            # Check for action verbs in the sentence
            words = word_tokenize(sentence_lower)

            # Simple verb check without relying on POS tagging
            if any(word in self.action_verbs for word in words):
                return True

            # Check if sentence starts with a verb (using spaCy)
            doc = nlp(sentence_lower)
            if len(doc) > 0 and doc[0].pos_ == "VERB":
                return True

            return False
        except Exception as e:
            print(f"Error in is_task_sentence: {str(e)}")
            return False

    def extract_tasks(self, text):
        """Main function to extract tasks from text."""
        try:
            # Preprocess the text
            cleaned_text = self.preprocess_text(text)

            # Split into sentences
            sentences = sent_tokenize(cleaned_text)

            # Store extracted tasks
            tasks = []

            for sentence in sentences:
                if self.is_task_sentence(sentence):
                    # Extract task components
                    person = self.extract_person(sentence)
                    deadline = self.extract_date_info(sentence)
                    category = self.categorize_task(sentence)

                    tasks.append({
                        'task': sentence.strip(),
                        'assignee': person,
                        'deadline': deadline,
                        'category': category
                    })

            return tasks
        except Exception as e:
            print(f"Error in extract_tasks: {str(e)}")
            return []

def main():
    # Example text with various tasks
    test_text = """
    John must complete the report by 5 pm today.
    Sarah needs to review the marketing materials before Thursday.
    Please clean the conference room by 3:00 pm.
    The team should implement the new feature by next week.
    Mary has to buy office supplies tomorrow.
    I am walking in the park right now.
    Tom is reading a book.
    We need to schedule a meeting with clients.
    """

    try:
        # Create task extractor instance
        extractor = TaskExtractor()

        # Extract tasks
        tasks = extractor.extract_tasks(test_text)

        # Print results
        print("Extracted Tasks:")
        print("-" * 50)
        for i, task in enumerate(tasks, 1):
            print(f"\nTask {i}:")
            print(f"Description: {task['task']}")
            print(f"Assignee: {task['assignee'] if task['assignee'] else 'Not specified'}")
            print(f"Deadline: {task['deadline'] if task['deadline'] else 'Not specified'}")
            print(f"Category: {task['category']}")
            print("-" * 50)

    except Exception as e:
        print(f"Error in main: {str(e)}")

if __name__ == "__main__":
    main()